version: '3'

services:
  postgres:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432'
  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www
    ports:
      - '8000:8000'
    depends_on:
      - postgres

volumes:
  postgres_data:
